# Doxygen ドキュメント生成と GitLab Pages 公開のための CI/CD パイプライン

stages:
  - lint
  - docs
  - deploy

# Lint/Format チェック（全ブランチ）
lint:
  stage: lint
  image: node:20-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm ci || npm i
  script:
    - npm run format:check
    - npm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH'

# DoxygenとGraphvizをインストールし、ドキュメントを生成するジョブ
# 全てのブランチで実行され、生成物をアーティファクトとして保存する
doxygen-docs:
  stage: docs
  image: debian:stable-slim
  before_script:
    - apt-get update -y && apt-get install -y doxygen graphviz
  script:
    - doxygen Doxyfile 2> docs/doxygen_warnings.log
  artifacts:
    paths:
      - docs/
    when: always
  rules:
    - if: '$CI_COMMIT_BRANCH'

# GitLab Pagesにドキュメントを公開するジョブ
# デフォルトブランチ（通常はmain）でのみ実行される
pages:
  stage: deploy
  image: alpine:latest
  script:


stages:
  - docs
  - deploy

doxygen-docs:
  image: debian:stable-slim
  stage: docs
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends doxygen graphviz ca-certificates && rm -rf /var/lib/apt/lists/*
    - mkdir -p docs
  script:
    - echo "Starting Doxygen generation..."
    - doxygen Doxyfile || echo "Doxygen failed but continuing..."
    - find docs -type f -name "*.html" | head -10 || echo "No HTML files found"
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - docs/
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  image: debian:stable-slim
  stage: deploy
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends doxygen graphviz ca-certificates && rm -rf /var/lib/apt/lists/*
    - mkdir -p docs public
  script:
    - doxygen Doxyfile || echo "Doxygen failed but continuing..."