image: alpine:3.19

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apk add --no-cache doxygen graphviz
    - doxygen Doxyfile
    - mkdir -p public
    - cp -r docs/html/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
