name: Docs & Pages

on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder build docs
        run: |
          echo "Building docs (placeholder)"

  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Placeholder deploy
        run: |
          echo "Deploying docs (placeholder)"
