name: Lint

on:
  push:
    paths:
      - '**/*.js'
      - '**/*.md'
      - 'package.json'
      - '.eslintrc.json'
      - '.prettierrc'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.md'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Prettier Check
        run: npm run format:check

      - name: ESLint
        run: npm run lint
