name: Project CI (shared)

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  ci-shared:
    uses: YuShimoji/shared-workflows/.github/workflows/ci-smoke.yml@c659f8f7057410c3684c39ac3796110aea6cfe3f
